# Generated by Django 5.1.3 on 2024-11-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_order_product_orderitem_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
